# Site settings
# Meta tags
title: Grantmakers.io - Grants Search
description: Discover who foundations are funding

# Jekyll settings
baseurl: /grants-search # Leave this blank unless your site is located on a subpath, e.g. /blog
url: https://www.grantmakers.io # Typically http://www.yourdomain.org
sass:
  sass_dir: assets/css/_sass

# Google Analytics
google-analytics: UA-84268197-1

# Sitewide helpers
algolia_link: http://goto.algolia.com/l/139121/2017-10-24/26gc84
number_of_grants: 3590885

# Build settings
markdown: kramdown
kramdown:
  input: GFM
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - node_modules
  - Creative_Tim_License.pdf